import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

from surgeon.llm import classify
from surgeon.redactor import redact

DEFAULT_THRESHOLD = 0.6


def _apply_patch(diff: str, repo_root: str) -> bool:
    result = subprocess.run(
        ["patch", "-p1", "--forward"],
        input=diff.encode(),
        cwd=repo_root,
        capture_output=True,
    )
    return result.returncode == 0


def _pr_body(diagnosis: dict) -> str:
    fc = diagnosis["failure_class"]
    conf = diagnosis["confidence"]
    tf = diagnosis.get("target_file") or "N/A"
    lines = [
        "## Pipeline Surgeon Diagnosis",
        "",
        f"**Failure class:** `{fc}`  ",
        f"**Confidence:** {conf:.0%}  ",
        f"**Target file:** `{tf}`",
        "",
        "### Root cause",
        "",
        diagnosis["root_cause"],
        "",
        "### Reasoning",
        "",
        diagnosis["reasoning"],
    ]
    if diagnosis.get("proposed_fix"):
        lines += [
            "",
            "### Proposed fix",
            "",
            "```diff",
            diagnosis["proposed_fix"],
            "```",
        ]
    lines += [
        "",
        "---",
        "_Generated by [pipeline-surgeon-labs](https://github.com/Kanim21/pipeline-surgeon-labs). "
        "Review carefully before merging._",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Maven CI failure diagnostician")
    parser.add_argument("--log", required=True, help="Path to Maven build log")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print diagnosis without modifying files",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=DEFAULT_THRESHOLD,
        help="Minimum confidence to apply fix (default: 0.6)",
    )
    parser.add_argument(
        "--output-diagnosis",
        default="diagnosis.json",
        help="Path to write diagnosis JSON",
    )
    parser.add_argument(
        "--output-pr-body",
        default="pr_body.md",
        help="Path to write PR body markdown",
    )
    args = parser.parse_args()

    log_path = Path(args.log)
    if not log_path.exists():
        print(f"ERROR: log file not found: {log_path}", file=sys.stderr)
        sys.exit(1)

    log_text = log_path.read_text(errors="replace")
    redacted = redact(log_text)

    print(f"[surgeon] classifying failure from {log_path} ...")
    diagnosis = classify(redacted)
    fc = diagnosis["failure_class"]
    conf = diagnosis["confidence"]
    print(f"[surgeon] {fc} (confidence={conf:.2f})")

    if not args.dry_run:
        with open(args.output_diagnosis, "w") as fh:
            json.dump(diagnosis, fh, indent=2)
        with open(args.output_pr_body, "w") as fh:
            fh.write(_pr_body(diagnosis))

    low_conf = conf < args.threshold
    no_fix = not diagnosis.get("proposed_fix")

    if low_conf or no_fix:
        reason = "low confidence" if low_conf else "no fix proposed"
        print(f"[surgeon] {reason} — opening diagnostic PR")
        sys.exit(2)

    if args.dry_run:
        print("[surgeon] DRY RUN — proposed fix:")
        print(diagnosis["proposed_fix"])
        return

    repo_root = os.environ.get("REPO_ROOT", ".")
    if _apply_patch(diagnosis["proposed_fix"], repo_root):
        print("[surgeon] patch applied successfully")
    else:
        print("[surgeon] patch failed to apply cleanly", file=sys.stderr)
        sys.exit(3)


if __name__ == "__main__":
    main()
